### ISSUE TITLE
Extra pane in Thunderbird 52

### ISSUE THREAD

**Issue by ribz** [absorb-it/Virtual-Identity#13]
I've just updated to Thunderbird 52 and Virtual-Identity appears to cause a new blank pane to appear at the bottom of every message window.

The identity selection drop down also seems to be broken in the compose window.

**Comment by absorb-it** [comment]
Hi Ed,

thanks for the report, the new version 0.9.35 should solve those issues. But be aware that its not well tested, please report if you have other issues with this release. Best regards,

Rene
