### ISSUE TITLE
VirtualIdentity Data Storage cannot set Base identity

### ISSUE THREAD

**Issue by n00b42** [absorb-it/Virtual-Identity#15]
Using the VirtualIdentity Data Storage I can not change the Base identity:

Reproduce:
- VirtualIdentity Data Storage
- Select entry & "Edit"
- Set SMTP & Base Identity
- "OK"
- SMTP is stored, Base Identity still shows empty

Background:
- I have 2 Base Identitys with the same domain name (a@domain.de, b@domain.de) and when I want to answer as "somewhat@domain.de" which belongs to b@domain.de it always shows "a@domain.de" and I have to change it otherwise my server rejects it.

Setup:
- Thunderbird 52.4.0 (64bit)

**Comment by absorb-it** [comment]
Hi,

thanks for this report, never realized that there is a problem. It's
fixed now with release 0.9.36.

Best Regards,
Rene

**Comment by n00b42** [comment]
Thank you for your quick fix. As far as I can tell it now works as expected :)

I actually feared you might have stopped working on this extension. I really like it and due to my extended use of catchall mail adresses I use it on a daily basis.

Regaeds
