### ISSUE TITLE
Virtual Identity is not compatible with Thunderbird 60

### ISSUE THREAD

**Issue by Wiiilmaa** [absorb-it/Virtual-Identity#19]
And i cannot use Thunderbird without it!

**Comment by absorb-it** [comment]
working on it, stay tuned...

**Comment by W-Hamra** [comment]
I've been checking your website almost weekly, and getting bummed by that "stable release is version ​0.9.36 from 23rd Nov 2017."

Really glad you haven't abandoned the project :)

**Comment by balu-** [comment]
looking forward to the version, thanks for working on it

**Comment by absorb-it** [comment]
Hi, version 0.10.1 is now compatible with TB60 (you can fin it as usual on https://www.absorb.it/virtual-id or via TBs update feature)... Please take care and provide feedback if some issues arise, it might require some intense testing.

Enjoy, regards, Rene

**Comment by lakano** [comment]
Works for me! Thanks a lot Rene!

**Comment by Wiiilmaa** [comment]
It Works like a charm, again! Thank you very much!
