### ISSUE TITLE
Please push your tags

### ISSUE THREAD

**Issue by llange** [absorb-it/Virtual-Identity#20]
Hello,
I may be wrong but it seems that your git tags are not pushed to GitHub.
(The last visible tag being 0.9.33, while latest version is 0.9.36).
The (minor) issue is that when trying to build the extension locally, `build.sh` will name it according to `git describe`, which is (currently) `0.9.33-19-g3c60682` instead of `0.9.36`.
A simple `git push --tags` should be all that is needed.
Thanks !

**Comment by absorb-it** [comment]
thanks for pointing to the issue, done. regards, Rene
